const mongoose = require("mongoose");

const clientCompanySchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
    trim: true,
    unique: true
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User"
  },
  createdAt: {
    type: Date,
    default: Date.now
  }
});

// Unique index is already generated by unique: true on name field

module.exports = mongoose.model("ClientCompany", clientCompanySchema);
